### ISSUE TITLE
multimode 

### ISSUE THREAD

**Issue by dutch66** [ArjanKranenburg/virtual-devices#37]
The multimode is a great addition for me. Only the choices in icons are very limited and do not match the modes I want to make. Is there a possibility to add icons yourself. At the moment I use the same icon for all modes and because there is no text there, this is not workable. It would be nice if the text of the mode name is also shown. Or a text only display when there is no option of additional icons.
![screenshot 412](https://user-images.githubusercontent.com/33862596/35280754-6cc630f2-0051-11e8-8498-ca4fd5800f37.jpg)

**Comment by ArjanKranenburg** [comment]
Hi,

Thanks for your report. I've tried adding titles, but it will show the capability value and somehow (probably since they are buttons) it is always 'turned on':
![image](https://user-images.githubusercontent.com/2014478/35592777-5fa3a23e-060e-11e8-8dbd-43d52f339d3d.png)
So that does not add any value and Athom does not provide means to specify anything else.

I will request Homey to add this functionality, but in the meantime I could add the icons that you want. Can you describe the icons or add them to this report?

Unfortunately icons cannot be uploaded at runtime (yet? see [Homey request #1972](https://github.com/athombv/homey/issues/1972)).

**Comment by dutch66** [comment]
Hi Arjan,

Thanks for the response.

At this moment I am not sure which icons I really need.
I was thinking themes like these:

  *   Morning
  *   Evening
  *   Night
  *   Day
  *   Lights high
  *   Lights middle
  *   Lights low
  *   Ambiance
  *   Reading
  *   Work
  *   Concentration

And maybe some general icons would be handy like A, B, C or -3, -2, -1, 0, 1, 2, 3 or a light bulbs (or other standard icon) with numbers or letters
And maybe icons for the default Philips Hue Sences

John



Van: Arjan Kranenburg [mailto:notifications@github.com]
Verzonden: dinsdag 30 januari 2018 22:59
Aan: ArjanKranenburg/virtual-devices <virtual-devices@noreply.github.com>
CC: John van Hoek <john@van-hoek.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ArjanKranenburg/virtual-devices] multimode (#37)


Hi,

Thanks for your report. I've tried adding titles, but it will show the capability value and somehow (probably since they are buttons) it is always 'turned on':
[image]<https://user-images.githubusercontent.com/2014478/35592777-5fa3a23e-060e-11e8-8dbd-43d52f339d3d.png>
So that does not add any value and Athom does not provide means to specify anything else.

I will request Homey to add this functionality, but in the meantime I could add the icons that you want. Can you describe the icons or add them to this report?

Unfortunately icons cannot be uploaded at runtime (yet? see Homey request #1972<https://github.com/athombv/homey/issues/1972>).

**Comment by dolfje** [comment]
Is it possible to preload all https://fontawesome.com free icons (900)?
I think we then have a full base set that is usable ;)
