### ISSUE TITLE
Unable to set Thermostate value with decimals

### ISSUE THREAD

**Issue by JohanBendz** [ArjanKranenburg/virtual-devices#43]
Hi there.

I am unable to set a value with decimals for the Thermostate using tags. If I round the value it works.

// Johan

**Comment by ArjanKranenburg** [comment]
Thanks for reporting. The target_temperature does allow 2 decimals, but the 'Set the temperature'-mobile card requires input in whole or half values (i.e. .50 or .00).
This is a standard Homey mobile card and unfortunately I cannot change that.

Do you use that mobile card? Otherwise can you share a flow picture or describe how you set the temperature?

**Comment by JohanBendz** [comment]
OK, thanks for getting back on that. Yes, I was using that card and if the solution is to round the value to half degrees that's what I'll do :)
