### ISSUE TITLE
The app crashes frequently

### ISSUE THREAD

**Issue by SmilingNL** [ArjanKranenburg/virtual-devices#44]
I have version 0.6.8 installed on Homey with firmware 1.5.8
The virtual devices app keeps crashing and this seems to affect the flows where the virtual device (mode) is used to determine if the flow should be executed. The app crashed 8 times over the last 15 days.

Is there anything you can help me with to get this issue solved?

Thank you!

**Comment by ArjanKranenburg** [comment]
Thanks for your report. Can you tell me a bit more:
Is it a particular flow? How does the flow look like?
Did you perhaps create or update the flow using the new Homey app?
Do you know what triggers a crash?
Anything else?

**Comment by SmilingNL** [comment]
Hi, I’m not sure if the flow crashes the app. The remark with the crash is that a report was sent to you, the developer. I use the mode virtual devices  I have created in quite some flows so no ideas which flow it is. I do have some issues with the flows executing when the virtual devices app has crashed. 

The mode virtual devices are mostly used by me in flows triggered by motion sensors. 

I most probably did do something on some or all of the flows with the beta iPhone app.

**Comment by ArjanKranenburg** [comment]
Hi,

Hmm, I didn't get any crash-reports since jan. 11th.
It looks a lot like issue #35, so I'll mark this as a duplicate and will close it.

There is 2 things you could do/try:
1. Recreate the flows with virtual devices in the desktop GUI.
2. Install the beta version of Virtual Devices. This will stop the crashes, but the flow will still not work. I believe the bug itself has to be fixed by Athom in their new App.
