### ISSUE TITLE
Setting that disables cascading triggering in then-column

### ISSUE THREAD

**Issue by ArjanKranenburg** [ArjanKranenburg/virtual-devices#5]

**Comment by ArjanKranenburg** [comment]
Solved for modes.

**Comment by MrZANE42** [comment]
Any chance this could be done for normal devices also? 
Either that of maybe a condition card that is true if triggered from flow otherwise false?

I have a looping problem, the device keeps turning on and off very fast when I activate both my flows for this device.
My setup is like this:
I have 2 flows, one that triggers on data from MQTT (Sonoff device running Tasmota) and with better logic decides if the device was turned on or off and then sets the state of the virtual device accordingly. The problem is that this triggers my second flow that is used to check if the status of the virtual device has changed and based on it's current state send an on or off command via MQTT. Currently that then triggers the first flow again since it gets info that the state has changed.

I'm aware that this can be done by adding one more flow with some additional logic but I rather not have too many flows for each device (if avoidable)

Thanks for all the time you put into this plug-in, it's one of the best and one I cant do without. 🥇

**Comment by ArjanKranenburg** [comment]
I've tried this, but unfortunately I cannot prevent Homey from triggering the device.
The difference with a mode is that a mode has a class 'other' which means I have to define the flow-cards which in turn means I can program the flow-cards as I like.

For devices with class light, button, tv, etc. Homey creates the cards for us. I can add a card that sets the state, but as soon as the state is changed, the auto-generated tirgger-card is triggered. I cannot prevent that.

I'm glad you have a workaround.
